const mk = (label, id, label2, id2, kind = 'sci') => ({
  label, id,
  label2: label2 ?? label,
  id2: id2 ?? id,
  kind,
});

export const SCI_BUTTONS = [
  mk('(', 'lparen'), mk(')', 'rparen'), mk('mc', 'mc'), mk('m+', 'mplus'), mk('m-', 'mminus'), mk('mr', 'mr'),
  mk('2ⁿᵈ', '2nd', '2ⁿᵈ', '2nd', 'sci2nd'),
  mk('x²', 'x2'), mk('x³', 'x3'),
  mk('xʸ', 'pow', 'ʸ√x', 'yroot'),
  mk('eˣ', 'ex', 'ln', 'ln'),
  mk('10ˣ', '10x', 'log₁₀', 'log10'),
  mk('¹/ₓ', '1/x'), mk('²√x', 'sqrt2'), mk('³√x', 'sqrt3'),
  mk('ʸ√x', 'yroot', 'xʸ', 'pow'),
  mk('ln', 'ln', 'eˣ', 'ex'),
  mk('log₁₀', 'log10', '10ˣ', '10x'),
  mk('x!', 'fact'),
  mk('sin', 'sin', 'sin⁻¹', 'asin'),
  mk('cos', 'cos', 'cos⁻¹', 'acos'),
  mk('tan', 'tan', 'tan⁻¹', 'atan'),
  mk('e', 'eConst'), mk('EE', 'ee'),
  mk('Rand', 'rand'),
  mk('sinh', 'sinh', 'sinh⁻¹', 'asinh'),
  mk('cosh', 'cosh', 'cosh⁻¹', 'acosh'),
  mk('tanh', 'tanh', 'tanh⁻¹', 'atanh'),
  mk('π', 'pi'),
  mk('Rad', 'radDeg', 'Deg', 'radDeg', 'sciMode'),
];

export const STD_BUTTONS = [
  { id: 'backspace', kind: 'fn', isBack: true },
  { label: 'AC',  id: 'clear',   kind: 'fn'  },
  { label: '%',   id: 'percent', kind: 'fn', style: { fontSize: '38px' } },
  { label: '÷',   id: '/',       kind: 'op', style: { transform: 'translateY(-6px)' } },
  { label: '7',   id: '7',       kind: 'num' },
  { label: '8',   id: '8',       kind: 'num' },
  { label: '9',   id: '9',       kind: 'num' },
  { label: '×',   id: 'x',       kind: 'op', style: { transform: 'translateY(-6px)' } },
  { label: '4',   id: '4',       kind: 'num' },
  { label: '5',   id: '5',       kind: 'num' },
  { label: '6',   id: '6',       kind: 'num' },
  { label: '−',   id: '-',       kind: 'op', style: { transform: 'translateY(-6px)' } },
  { label: '1',   id: '1',       kind: 'num' },
  { label: '2',   id: '2',       kind: 'num' },
  { label: '3',   id: '3',       kind: 'num' },
  { label: '+',   id: '+',       kind: 'op', style: { transform: 'translateY(-6px)' } },
  { label: '+/-', id: 'negate',  kind: 'fn'  },
  { label: '0',   id: '0',       kind: 'num' },
  { label: '.',   id: '.',       kind: 'num' },
  { label: '=',   id: '=',       kind: 'op'  },
];
